import { getCategoryIcon } from '../utils/quizUtils';
import { calculateOverviewStats } from '../utils/statisticsUtils';

/**
 * Dashboard View Component - Phase 4
 * Learner portal showing real persisted stats computed via statisticsUtils
 */
export default function Dashboard({
  onNavigateView,
  flashcards = [],
  quizHistory = []
}) {
  const overview = calculateOverviewStats(flashcards, quizHistory);

  // Compute category breakdown from active flashcards
  const categoryCounts = {};
  flashcards.forEach((card) => {
    const cat = card.category || 'General';
    categoryCounts[cat] = (categoryCounts[cat] || 0) + 1;
  });

  const categoriesList = Object.keys(categoryCounts).map((catName) => ({
    name: catName,
    count: categoryCounts[catName],
    icon: getCategoryIcon(catName)
  }));

  return (
    <div className="dashboard-container">
      {/* 1. User-Neutral Welcome Banner */}
      <section className="welcome-banner">
        <div className="welcome-content">
          <div className="welcome-pill">⚡ Learning Workspace</div>
          <h1 className="welcome-title">Ready to learn something new?</h1>
          <p className="welcome-subtitle">
            Create flashcards, test your knowledge, or challenge others.
          </p>
          <div className="welcome-actions">
            <button
              type="button"
              className="btn btn-primary"
              onClick={() => onNavigateView('flashcards')}
            >
              <span>Explore Flashcards</span>
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <line x1="5" y1="12" x2="19" y2="12" />
                <polyline points="12 5 19 12 12 19" />
              </svg>
            </button>
            <button
              type="button"
              className="btn btn-secondary"
              onClick={() => onNavigateView('mock-quiz')}
            >
              <span>Start Mock Quiz 🚀</span>
            </button>
          </div>
        </div>
        <div className="welcome-illustration">
          <div className="card-stack-decoration">
            <div className="deco-card card-3">DBMS 🗄️</div>
            <div className="deco-card card-2">React ⚛️</div>
            <div className="deco-card card-1">JavaScript 🟨</div>
          </div>
        </div>
      </section>

      {/* 2. Three Primary Experience Cards */}
      <section className="dashboard-section">
        <h3 className="section-title">Core Learning Experiences</h3>
        <div className="three-cards-grid">
          {/* Flashcards (Create / Study) */}
          <div
            className="feature-card learning-card"
            onClick={() => onNavigateView('flashcards')}
          >
            <div className="feature-card-header">
              <div className="feature-icon-box purple">🎴</div>
              <span className="badge badge-purple">Active Mode</span>
            </div>
            <div className="feature-card-meta">
              <span className="feature-mode-label">CREATE & STUDY</span>
              <h4 className="feature-card-title">Flashcards</h4>
            </div>
            <p className="feature-card-desc">
              Build, edit, organize, and flip through custom flashcard decks with persistent study tracking.
            </p>
            <div className="feature-card-footer">
              <span className="feature-cta-btn primary-cta">Open Flashcards →</span>
            </div>
          </div>

          {/* Mock Quiz (Self-Assessment) */}
          <div
            className="feature-card assessment-card"
            onClick={() => onNavigateView('mock-quiz')}
          >
            <div className="feature-card-header">
              <div className="feature-icon-box blue">📝</div>
              <span className="badge badge-purple">Active Mode</span>
            </div>
            <div className="feature-card-meta">
              <span className="feature-mode-label">SELF-ASSESS</span>
              <h4 className="feature-card-title">Mock Quiz</h4>
            </div>
            <p className="feature-card-desc">
              Test yourself with a solo practice quiz generated by the application based on your parameters.
            </p>
            <div className="feature-card-footer">
              <span className="feature-cta-btn primary-cta">Start Mock Quiz →</span>
            </div>
          </div>

          {/* Live Quiz */}
          <div
            className="feature-card competition-card"
            onClick={() => onNavigateView('live-quiz')}
          >
            <div className="feature-card-header">
              <div className="feature-icon-box amber">⚡</div>
              <span className="badge badge-disabled">Coming Soon</span>
            </div>
            <div className="feature-card-meta">
              <span className="feature-mode-label">COMPETE</span>
              <h4 className="feature-card-title">Live Quiz</h4>
            </div>
            <p className="feature-card-desc">
              Host a live quiz room or join with a room code to compete against classmates in real-time.
            </p>
            <div className="feature-card-footer">
              <span className="feature-cta-btn secondary-cta">Preview Concept →</span>
            </div>
          </div>
        </div>
      </section>

      {/* 3. Real Persisted Overview Stats */}
      <section className="dashboard-stats-grid">
        <div className="stat-card">
          <div className="stat-icon-wrapper purple">📚</div>
          <div className="stat-details">
            <span className="stat-value">{overview.totalCards}</span>
            <span className="stat-label">Total Flashcards</span>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon-wrapper blue">🎯</div>
          <div className="stat-details">
            <span className="stat-value">{overview.quizzesCompleted}</span>
            <span className="stat-label">Quizzes Completed</span>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon-wrapper green">📖</div>
          <div className="stat-details">
            <span className="stat-value">{overview.totalStudied}</span>
            <span className="stat-label">Cards Studied</span>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon-wrapper amber">🏆</div>
          <div className="stat-details">
            <span className="stat-value">{overview.averageScore}%</span>
            <span className="stat-label">Overall Accuracy</span>
          </div>
        </div>
      </section>

      {/* 4. Categories Overview Section */}
      <section className="dashboard-section">
        <div className="section-header-flex">
          <h3 className="section-title">Categories Breakdown</h3>
          <button
            type="button"
            className="text-link"
            onClick={() => onNavigateView('flashcards')}
          >
            View All Cards →
          </button>
        </div>

        <div className="categories-grid">
          {categoriesList.map((cat) => (
            <div key={cat.name} className="category-card" onClick={() => onNavigateView('flashcards')}>
              <div className="category-icon">{cat.icon}</div>
              <div className="category-info">
                <h4 className="category-name">{cat.name}</h4>
                <span className="category-count">{cat.count} {cat.count === 1 ? 'Flashcard' : 'Flashcards'}</span>
              </div>
              <span className="category-arrow">→</span>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
