import { sampleCategories } from '../data/defaultFlashcards';

/**
 * Dashboard View Component - Phase 1.5
 * User-neutral learning portal featuring the 3 core learning modes (Flashcards, Mock Quiz, Live Quiz)
 */
export default function Dashboard({ onNavigateView, flashcardsCount }) {
  return (
    <div className="dashboard-container">
      {/* 1. User-Neutral Welcome Banner */}
      <section className="welcome-banner">
        <div className="welcome-content">
          <div className="welcome-pill">⚡ Learning Workspace</div>
          <h1 className="welcome-title">Ready to learn something new?</h1>
          <p className="welcome-subtitle">
            Create flashcards, test your knowledge, or challenge others.
          </p>
          <div className="welcome-actions">
            <button
              type="button"
              className="btn btn-primary"
              onClick={() => onNavigateView('flashcards')}
            >
              <span>Explore Flashcards</span>
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <line x1="5" y1="12" x2="19" y2="12" />
                <polyline points="12 5 19 12 12 19" />
              </svg>
            </button>
            <button
              type="button"
              className="btn btn-secondary"
              onClick={() => onNavigateView('mock-quiz')}
            >
              <span>Explore Mock Quiz</span>
              <span className="badge badge-purple">Preview</span>
            </button>
          </div>
        </div>
        <div className="welcome-illustration">
          <div className="card-stack-decoration">
            <div className="deco-card card-3">DBMS 🗄️</div>
            <div className="deco-card card-2">React ⚛️</div>
            <div className="deco-card card-1">JavaScript 🟨</div>
          </div>
        </div>
      </section>

      {/* 2. Three Distinct Primary Experience Cards */}
      <section className="dashboard-section">
        <h3 className="section-title">Core Learning Experiences</h3>
        <div className="three-cards-grid">

          {/* Experience 1: Flashcards (Create / Study) */}
          <div
            className="feature-card learning-card"
            onClick={() => onNavigateView('flashcards')}
          >
            <div className="feature-card-header">
              <div className="feature-icon-box purple">🎴</div>
              <span className="badge badge-purple">Active Mode</span>
            </div>
            <div className="feature-card-meta">
              <span className="feature-mode-label">CREATE & STUDY</span>
              <h4 className="feature-card-title">Flashcards</h4>
            </div>
            <p className="feature-card-desc">
              Build, organize, and flip through custom flashcard decks to master key technical concepts.
            </p>
            <div className="feature-card-footer">
              <span className="feature-cta-btn primary-cta">Open Flashcards →</span>
            </div>
          </div>

          {/* Experience 2: Mock Quiz (Self-Assessment) */}
          <div
            className="feature-card assessment-card"
            onClick={() => onNavigateView('mock-quiz')}
          >
            <div className="feature-card-header">
              <div className="feature-icon-box blue">📝</div>
              <span className="badge badge-disabled">Coming Soon</span>
            </div>
            <div className="feature-card-meta">
              <span className="feature-mode-label">SELF-ASSESS</span>
              <h4 className="feature-card-title">Mock Quiz</h4>
            </div>
            <p className="feature-card-desc">
              Test yourself with a solo practice quiz generated by the application based on your chosen parameters.
            </p>
            <div className="feature-card-footer">
              <span className="feature-cta-btn secondary-cta">Preview Concept →</span>
            </div>
          </div>

          {/* Experience 3: Live Quiz (Real-Time Competition) */}
          <div
            className="feature-card competition-card"
            onClick={() => onNavigateView('live-quiz')}
          >
            <div className="feature-card-header">
              <div className="feature-icon-box amber">⚡</div>
              <span className="badge badge-disabled">Coming Soon</span>
            </div>
            <div className="feature-card-meta">
              <span className="feature-mode-label">COMPETE</span>
              <h4 className="feature-card-title">Live Quiz</h4>
            </div>
            <p className="feature-card-desc">
              Host a live quiz room or join with a room code to compete against classmates in real-time.
            </p>
            <div className="feature-card-footer">
              <span className="feature-cta-btn secondary-cta">Preview Concept →</span>
            </div>
          </div>

        </div>
      </section>

      {/* 3. Truthful Progress Stats */}
      <section className="dashboard-stats-grid">
        <div className="stat-card">
          <div className="stat-icon-wrapper purple">📚</div>
          <div className="stat-details">
            <span className="stat-value">{flashcardsCount}</span>
            <span className="stat-label">Total Flashcards</span>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon-wrapper blue">🎯</div>
          <div className="stat-details">
            <span className="stat-value">0</span>
            <span className="stat-label">Quizzes Completed</span>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon-wrapper green">📖</div>
          <div className="stat-details">
            <span className="stat-value">0</span>
            <span className="stat-label">Cards Studied</span>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon-wrapper amber">🏆</div>
          <div className="stat-details">
            <span className="stat-value">0%</span>
            <span className="stat-label">Overall Accuracy</span>
          </div>
        </div>
      </section>

      {/* 4. Categories Overview Section */}
      <section className="dashboard-section">
        <div className="section-header-flex">
          <h3 className="section-title">Flashcard Categories</h3>
          <button
            type="button"
            className="text-link"
            onClick={() => onNavigateView('flashcards')}
          >
            View All Cards →
          </button>
        </div>

        <div className="categories-grid">
          {sampleCategories.filter(c => c.id !== 'cat-all').map((cat) => (
            <div key={cat.id} className="category-card" onClick={() => onNavigateView('flashcards')}>
              <div className="category-icon">{cat.icon}</div>
              <div className="category-info">
                <h4 className="category-name">{cat.name}</h4>
                <span className="category-count">{cat.count} Flashcards</span>
              </div>
              <span className="category-arrow">→</span>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
